### ISSUE TITLE
Configure project so react-native-web npm lib can be used in reagent forms

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#1]
https://github.com/necolas/react-native-web

You can find how we use this lib in status-electron app 
https://github.com/status-im/status-electron/blob/master/src_front/status_desktop_front/react_native_web.cljs
https://github.com/status-im/status-electron/blob/master/src_front/status_desktop_front/ui/screens/views.cljs#L3

It should be possible to render same views in web project

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2500.00
Contract address: [0x5cf3da4d17b83b07a73fe6b706e9d394113052cf](https://etherscan.io/address/0x5cf3da4d17b83b07a73fe6b706e9d394113052cf)
Network: Mainnet
Paid to: foopang
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by vemv** [comment]
I assume you attempted to do this yourselves at least once, what difficulties did you find?
