### ISSUE TITLE
Implement `status-im.ui.components.toolbar` support

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#13]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc2b9109a978d72c576ec233a86107fd414747de5ec5599699c613f226d42bf72](https://etherscan.io/tx/0xc2b9109a978d72c576ec233a86107fd414747de5ec5599699c613f226d42bf72)
