### ISSUE TITLE
Implement data generation for lists

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#15]
it should be possible to generate some fake data for lists using spec

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x280ae4b918b3784121f30af80fa0f03f546e10dd9258e8c43716757a894d9e58](https://etherscan.io/tx/0x280ae4b918b3784121f30af80fa0f03f546e10dd9258e8c43716757a894d9e58)

**Comment by audriu** [comment]
I guess this one means that we need a "spec" to be written for list of something.
And then make namespace with a function which uses "gen" and returns the data generated.
what exactly will be in the list or will we create specs later?

**Comment by audriu** [comment]
@flexsurfer I guess this one means that we need a "spec" to be written for list of something.
And then make namespace with a function which uses ["gen"](https://clojure.org/about/spec) and returns the data generated.
what exactly will be in the list or will we create specs later?
something like: [here](https://stackoverflow.com/questions/43920066/creating-a-clojure-spec-generator-for-a-nested-data-structure-with-constraints-a)

**Comment by audriu** [comment]
Issue moved to [status-im/autobounty #3](https://github.com/status-im/autobounty/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by audriu** [comment]
could you please elaborate what date to be generated exactly?

**Comment by flexsurfer** [comment]
@audriu lets postpone it for now
