### ISSUE TITLE
Implement parinfer editor and autocompile react native views

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#3]
Implement similar functionality to http://escherize.com/cljsfiddle/, with the next differences 
1) page should be simpler - only two forms, code editor and a resulting view
2) compilation should be automatic (with error handling), no run button
3) code for parinfer editor should be as simple as possible with minimum assets
4) it should be possible to enter react-native-web components and see the result 

![image](https://user-images.githubusercontent.com/11790366/34514998-1ec10448-f081-11e7-875c-774c32ada08d.png)

  **Edited**: please see comments to https://github.com/status-im/status-fiddle/pull/5

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1100.00
Contract address: [0x56b5812c4dee81ec744c75fc47a75975c7adab19](https://etherscan.io/address/0x56b5812c4dee81ec744c75fc47a75975c7adab19)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by poiga** [comment]
I am working on this!

**Comment by flexsurfer** [comment]
hey @poiga do you want to continue work? or maybe @foopang wants to try?

**Comment by poiga** [comment]
@flexsurfer I am continuing :)

**Comment by foopang** [comment]
@flexsurfer thanks for inviting me to work on it, maybe I can try next time. I am pretty sure @poiga can deliver better work than I do :)

**Comment by shaunlebron** [comment]
@poiga @flexsurfer 

👋 Just a heads up—it's much easier to use Parinfer through the official [parinfer-codemirror] library now.  I'm on call for questions!

[parinfer-codemirror]:https://github.com/shaunlebron/parinfer-codemirror

**Comment by ghost** [comment]
@shaunlebron any CDNs for that?

**Comment by flexsurfer** [comment]
that's cool @shaunlebron , thanks , i'll take a look how we can use it

**Comment by shaunlebron** [comment]
@poiga you can use [unpkg](https://unpkg.com)

- https://unpkg.com/parinfer@3.12.0/parinfer.js
- https://unpkg.com/parinfer-codemirror@1.4.2/parinfer-codemirror.js

**Comment by flexsurfer** [comment]
@poiga added little bit SNT for research

**Comment by flexsurfer** [comment]
@poiga https://github.com/shaunlebron/parinfer-codemirror/blob/master/demo.html this looks much simpler, so we need just to "add" `CodeMirror` to reagent form and listen to cm content changes

**Comment by ghost** [comment]
@flexsurfer I will Inversigate

**Comment by ghost** [comment]
@shaunlebron I am searching for some "on edit" callback for 'cm = CodeMirror(document.body);' instance. any advice please?

**Comment by shaunlebron** [comment]
@poiga try [`cm.on('change', ...)`](https://codemirror.net/doc/manual.html#event_change) or [`cm.on('changes', ...)`](https://codemirror.net/doc/manual.html#event_changes)

**Comment by shaunlebron** [comment]
@poiga btw, Parinfer will not try to correct code when changes come from [`cm.setValue`](https://codemirror.net/doc/manual.html#setValue)—this helps us avoid reaction loops.  So it _should_ be okay syncing your reagent state with CodeMirror using `setValue` after receiving its value from [`cm.getValue`](https://codemirror.net/doc/manual.html#getValue) inside `on('change')`, if that's what you're trying.

I personally have been bitten too much by trying to use React to control the state of components not designed for React, so you may wanna avoid it completely.  But I'm here for questions whichever you decide.

**Comment by ghost** [comment]
@shaunlebron I am working on https://github.com/poiga/status-fiddle/blob/some-work-with-cljsfiddle/src/cljs/status_fiddle/views.cljs line 15.
Looks like this lib does the job. Nice!

**Comment by shaunlebron** [comment]
@poiga @flexsurfer Great work!  Please let me know if something is misbehaving with parinfer-codemirror!  My incentive is to make it very solid, so I'm willing to change/fix things depending on how people are using.  Thanks! 👍
