### ISSUE TITLE
Implement save functionality

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#8]
there should be autosave functionality, last valid state should be saved in localstorage, also it should be possible to share your work (maybe gist?) gist example https://gitlab.com/escherize/cljsfiddle/blob/master/src/cljs/cljsfiddle/gist.cljs

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 780.00
Contract address: [0xb567eb6c87f8b56df0db476353b45808d739850d](https://etherscan.io/address/0xb567eb6c87f8b56df0db476353b45808d739850d)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
