### ISSUE TITLE
Implement all popular mobile device sizes and platform support

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-fiddle#9]
we have only one size - iphone6, it should be possible to choose any popular device android or ios
also there should be platform support in the editor, so we can show differences in views for ios and android https://github.com/status-im/status-fiddle/blob/master/src/cljs/status_im/utils/platform.cljs

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 780.00
Contract address: [0x9b7382bee020638f8c7b2905e4b9e19c5f0fc857](https://etherscan.io/address/0x9b7382bee020638f8c7b2905e4b9e19c5f0fc857)
Network: Mainnet
Paid to: poiga
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by poiga** [comment]
I am working on this!

**Comment by ghost** [comment]
I have investigated  [discussion](https://github.com/status-im/status-react/issues/2752) on the topic. And IMO it would be reasonable to include 5 most popular [androids](https://www.appbrain.com/stats/top-android-phones) and so 5 most recent IPhones. Thoughts?

**Comment by flexsurfer** [comment]
yeah, so this issue has the wrong description, the idea is to see how it looks on different resolutions, most popular have same sizes, so it should be all ios resolutions starting from iphone4 https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions
and 5 popular android resolutions but different resolutions not devices

**Comment by flexsurfer** [comment]
and one more thing we should use points not pixels

**Comment by ghost** [comment]
@flexsurfer  I have changed my Github handle - I hope it wont be a problem for the smart contract...

**Comment by flexsurfer** [comment]
i think it should be fine @audriu because here https://openbounty.status.im/app it looks fine
